version: '3'
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
    expose:
      - '8080'
    networks:
      - mysql_network
  mysql_db:
    container_name: mysql_container
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_DATABASE: 'user_db'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      - '3306'
      - '3308'
    networks:
      - mysql_network
#  mysql-workbench:
#    image: lscr.io/linuxserver/mysql-workbench
#    container_name: mysql-workbench
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#    volumes:
#      - /path/to/config:/config
#    ports:
#      - 3000:3000
#    cap_add:
#      - IPC_LOCK
#    restart: unless-stopped
#    networks:
#      - mysql_network
networks:
  mysql_network:
    driver: bridge