spring:
  application:
    name: "grocery-booking-api"

  datasource:
    username: 'root' #${MYSQL_USER}
    password: 'root' #${MYSQL_PASSWORD}
    url: "jdbc:mysql://localhost:3306/user_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true" #${MYSQL_URL}
#    url: "jdbc:mysql://localhost:3308/user_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true" #${MYSQL_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080